version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webapp:/var/www/html

  wordpress:
    image: wordpress:php7.3-fpm-alpine
    restart: always
    volumes:
      - ./webapp:/var/www/html