version: "3"

services:
  web:
    container_name: laravel-alpine-web
    build: ./.docker/nginx
    volumes:
      - ./.docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:z
      - ./app:/app
    ports:
      - 80:8080
    restart: always
    depends_on:
      - php
      - db
  php:
    container_name: laravel-alpine-php
    build: ./.docker/php
    restart: always
    volumes:
      - ./.docker/php/conf/php.ini:/usr/local/etc/php/php.ini:z
      - ./app:/app
      - ./phpinfo/phpinfo.php:/var/www/html/phpinfo.php:z
  db:
    container_name: laravel-alpine-db
    image: mysql:latest
    volumes:
      - ./.docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf:z
      - ./.docker/mysql/wait_sh.sh:/root/wait_sh.sh:z
    restart: always
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.34.0/24
